### ISSUE TITLE
Bot não atinge os requisitos mínimos

### ISSUE THREAD

**Issue by MarianaFL** [RicardoBusta/BustaBot#1]
O funcionamento do jogo de música com esse bot deveria seguir o seguinte fluxo:
Quando uma pessoa postasse a música ela chamava o bot dizendo quem era o próximo e qual a música do dia.
Ele escreveria e daria pin numa mensagem em que listaria quem falta (sem @), quem é o próximo (com @) e colocaria o link da música escolhida.
Se acontecer de uma pessoa não postar a música por dois dias seguidos ele automaticamente skippa e escolhe alguém que ainda não foi aleatoriamente. Note que esse período não é de 48h, se o próximo foi escolhido às 23h do dia 1, ele skipparia no começo do dia 4 (talvez seja bom skippar num horário específico tipo de manhã só pra não taggear ninguém logo na meia-noite, não sei, fica aí a reflexão)
Os comandos básicos que precisamos é o de listar todos participantes (mesmo os que já foram na rodada), adicionar pessoas na lista, remover pessoas na lista, chamar o próximo pra escolher a música e um skip manual (as vezes alguém não quer escolher a música daquela vez).

**Comment by ricardobusta** [comment]
Tá faltando uma coisinha pra possibilitar dar pin na mensagem que é conseguir identificar o objeto body que a request tá retornando. Assim que eu entender eu vou conseguir pegar o message_id e mandar um comando de pin nela. 

Acho que tirando isso, falta só parar de sortear o próximo aleatoriamente e fazer isso recebendo o username por parâmetro.
